compiler/src/main/kotlin/se/ansman/kotshi/DefaultValueProviders.kt, tests/src/main/kotlin/se/ansman/kotshi/ClassWithGenericDefaults.kt
The bug could cause an invalid provider to be picked if there was a
provider that provides a subclass with fewer generic type parameters
existed.
So for example if you had a property of the type `Map<String, String>`
and a subclass to map called `IntMap<T> : Map<Int, T>` and a generic
provider for that subclass then that provider would be used and thus the
generated code would not compile.
=> Fix a bug that caused uncompilable code to be generated

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
This allows the adapter to fail sooner if the JSON is not actually an object.
=> Read object opening before initializing locals.

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
This saves emitting a jump to the end of the method only to return and visually reduces nesting.
=> When writing null, perform an an early return.

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
Before:
```java
if (!aBooleanIsSet) {
stringBuilder = KotshiUtils.appendNullableError(stringBuilder, "aBoolean");
}
if (aNullableBoolean == null) {
}
if (!aByteIsSet) {
stringBuilder = KotshiUtils.appendNullableError(stringBuilder, "aByte");
}
```
After:
```java
if (!aBooleanIsSet) {
stringBuilder = KotshiUtils.appendNullableError(stringBuilder, "aBoolean");
}
if (!aByteIsSet) {
stringBuilder = KotshiUtils.appendNullableError(stringBuilder, "aByte");
}
```
=> Eliminate superfluous null check on allowed-nullable values.

api/src/main/kotlin/se/ansman/kotshi/KotshiUtils.kt, compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
JavaWriter has Booean and Number overloads to value() which handle null. Add boxed overloads to custom Char and Byte handlers.
=> Remove explicit null check for boxed primitives in writer.

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
This also uses the $S JavaPoet replacement to emit the string literals, as it will handle things like escaping, should some crazy person use a tab or emoji as their JSON key.
Before:
```java
private static final JsonReader.Options OPTIONS = JsonReader.Options.of("aBoolean", "aNullableBoolean", "aByte", ...);
```
After:
```java
private static final JsonReader.Options OPTIONS = JsonReader.Options.of(
"aBoolean",
"aNullableBoolean",
"aByte",
"nullableByte",
"aChar",
"nullableChar",
"aShort",
"nullableShort",
"integer",
"nullableInteger",
"aLong",
"nullableLong",
"aFloat",
"nullableFloat",
"aDouble",
"nullableDouble");
```
=> Wrap the JSON name strings onto one per-line.

.gitignore
If you have `--profile` enabled by default (which I do) and Gradle configuration fails it dumps things into `report/`. Also `*.iml`s from IDEA/AS shouldn't be commited since Gradle is the source of truth for build config.
=> Add IDE imls and Gradle's reports dir to ignores.

README.md
The custom default value annotation `StringWithNA` was missing it's `@JsonDefaultValue` annotation.
I added it along with a comment to make it clear how important it is among the annotations boilerplate
(namely: `@Target`, `@MustBeDocumented` and `@Retention`)
=> Fix missing @JsonDefaultValue on custom annotation

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt, compiler/src/main/kotlin/se/ansman/kotshi/FactoryProcessingStep.kt, compiler/src/main/kotlin/se/ansman/kotshi/GeneratedAdapter.kt, compiler/src/main/kotlin/se/ansman/kotshi/KotshiProcessor.kt, tests/src/main/kotlin/se/ansman/kotshi/ClassWithWeirdNames.kt
This also removes "types" and "moshi" from the allocated names as they are not used in methods where collisions could occur.
Closes #26.
=> Do not pass Moshi instance to adapter when not needed.

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt, compiler/src/main/kotlin/se/ansman/kotshi/Property.kt, tests/src/main/kotlin/se/ansman/kotshi/UseAdaptersPerDefault.kt, tests/src/test/kotlin/se/ansman/kotshi/TestPrimitiveAdapters.kt
=> Treat strings as primitive values and skip adapters per default

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt, compiler/src/main/kotlin/se/ansman/kotshi/MethodSpecExt.kt
This avoids having to jump way ahead to the end of the switch bytecodes only to jump way back to the loop conditional.
=> Do a direct continue inside switch cases.

README.md
The `@JsonDefaultValue` example snippet had a 2 spaces indentation while the other snippets have a 4 spaces one.
=> Fix inconsistent indentation in README snippet

tests/src/main/kotlin/se/ansman/kotshi/UseAdaptersPerDefault.kt, tests/src/test/kotlin/se/ansman/kotshi/TestPrimitiveAdapters.kt
=> Add a test for qualified primitive always calling an adapter.

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt, compiler/src/main/kotlin/se/ansman/kotshi/DefaultValueProviders.kt, compiler/src/main/kotlin/se/ansman/kotshi/Property.kt, tests/src/main/kotlin/se/ansman/kotshi/ClassWithJavaKeyword.kt, tests/src/test/kotlin/se/ansman/kotshi/TestClassWithJavaKeyword.kt
Here is a sample class that would fail compilation before this change:
```kotlin
data class Foo(@Json(name="default") @GetterName("getDefault") val default: Boolean)
```
=> Handle properties names as java keywords such as default better

README.md, compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt, compiler/src/main/kotlin/se/ansman/kotshi/DefaultValueProviders.kt, compiler/src/main/kotlin/se/ansman/kotshi/Property.kt, tests/src/main/kotlin/se/ansman/kotshi/ClassWithTransient.kt, tests/src/test/kotlin/se/ansman/kotshi/TestTransientAdapters.kt
Closes #78.
* Allows user to specify `@Transient` for a data class field.
* Transient fields are not output to JSON
* Transient field data in incoming JSON is ignored
* A `@JsonDefaultValue` must be supplied somehow (but `@JsonDefaultValue` need not be specified explicitly on the field itself)
=> Add support for @Transient modifier

build.gradle
kotlin-stdlib-jre7 is deprecated.
Also updated Kotlin version to 1.2.40, which contains the deprecation warning.
Fixes https://github.com/ansman/kotshi/issues/83
=> Replace kotlin-stdlib-jre7 with kotlin-stdlib-jdk7.

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt, compiler/src/main/kotlin/se/ansman/kotshi/FactoryProcessingStep.kt, tests/src/main/kotlin/se/ansman/kotshi/InternalClass.kt
This might break things from some people but I doubt many people rely on accessing the generated adapters or factories from other modules.
=> Make generated adapters and factories internal

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt, tests/src/main/kotlin/se/ansman/kotshi/LongClassName.kt
Kotlinpoet will allow breaking for spaces but this can sometimes lead to
invalid code. Now we prevent breaking for those cases.
This fixes #123
=> Fix invalid code from being generated for long class or property names

README.md, api/src/main/kotlin/se/ansman/kotshi/KotshiJsonAdapterFactory.kt, compiler/src/main/kotlin/se/ansman/kotshi/KotshiProcessor.kt
Instead of having to make the factory abstract and have a static
INSTANCE field factories can now be an `object` that delegates the
adapter creation to the generated factory.
This was done previously but there was issues but those seems to have
been caused by SuperficialValidation.validateElement returning false for
the factory class in some cases. It doesn't seem like that call is
needed so now the generation has been simplified.
=> Improve how to implement the factory

api/src/main/kotlin/se/ansman/kotshi/KotshiUtils.kt
KotshiUtils was updated and was not binary compatible meaning Kotshi adapters in libraries would expect the old method for appending errors which does not exist on the new version.
=> Fix a crash that can happen when using adapters from a library

compiler/src/main/kotlin/se/ansman/kotshi/generators/DataClassAdapterGenerator.kt, tests/src/main/kotlin/se/ansman/kotshi/GenericClass.kt, tests/src/test/kotlin/se/ansman/kotshi/TestAdapterGeneration.kt
This is required when using `@RawValue` on Android for example.
=> Fix annotating generic types with an annotation

compiler/src/main/kotlin/se/ansman/kotshi/Property.kt, compiler/src/main/kotlin/se/ansman/kotshi/generators/DataClassAdapterGenerator.kt
Type annotations should not be considered when comparing adapter keys since
they don't affect which adapter that is returned. Now the annotations
are ignored and fewer adapters are requested. The performance impact
will be miniscule however since Moshi caches adapters.
=> Reduce the number of adapters that are fetched

api/src/main/kotlin/se/ansman/kotshi/Polymorphic.kt, compiler/src/main/kotlin/se/ansman/kotshi/generators/SealedClassAdapterGenerator.kt, tests/src/main/kotlin/se/ansman/kotshi/SealedClassOnInvalidFail.kt, tests/src/main/kotlin/se/ansman/kotshi/SealedClassOnInvalidNull.kt, tests/src/main/kotlin/se/ansman/kotshi/SealedClassOnMissingFail.kt, tests/src/main/kotlin/se/ansman/kotshi/SealedClassOnMissingNull.kt, tests/src/test/kotlin/se/ansman/kotshi/SealedClassFallbacks.kt
By default the default will be used if one exists otherwise parsing will
fail with a `JsonDataException`. There are no two additional fallback
modes. One will always fail parsing and one will return `null`.
=> Allow specifying sealed class behavior for missing and invalid labels

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt, compiler/src/main/kotlin/se/ansman/kotshi/KotshiProcessor.kt, compiler/src/main/kotlin/se/ansman/kotshi/generators/AdapterGenerator.kt, compiler/src/main/kotlin/se/ansman/kotshi/generators/DataClassAdapterGenerator.kt, compiler/src/main/kotlin/se/ansman/kotshi/generators/EnumAdapterGenerator.kt, compiler/src/main/kotlin/se/ansman/kotshi/generators/ObjectAdapterGenerator.kt, compiler/src/main/kotlin/se/ansman/kotshi/generators/SealedClassAdapterGenerator.kt, tests/src/main/kotlin/se/ansman/kotshi/SealedClassWithExistingLabel.kt, tests/src/test/kotlin/se/ansman/kotshi/NestedSealedClassTest.kt, tests/src/test/kotlin/se/ansman/kotshi/SealedClassWithDefaultWithTypeTest.kt, tests/src/test/kotlin/se/ansman/kotshi/SealedClassWithDefaultWithoutTypeTest.kt, tests/src/test/kotlin/se/ansman/kotshi/SealedClassWithExistingLabelTest.kt, tests/src/test/kotlin/se/ansman/kotshi/SealedClassWithoutDefaultTest.kt
The adapters in Kotshi currently drop the label when serializing, which makes working with `sealed class` hierarchies cumbersome (e.g. cannot use `object` when serializing, must add a `val label: String = "labelKey"` default to data classes). This commit aims to fix this by emitting labels implicitly for sealed classes if they're not already present as a property.
NOTE: this is a pretty big breaking change, maybe this should be a parameter on `@Polymorphic` that defaults to false? E.g. `@Polymorphic(labelKey = "type")` to keep the current behaviour and `@Polymorphic(labelKey = "type", serializeLabels = true)` to get the new one?
---
Example adapter `toJson` function of a `data class`:
```
@Throws(IOException::class)
override fun toJson(writer: JsonWriter, value: …
```
=> Emit labels when serializing sealed class subtypes

gradle/kotlin.gradle
This will ensure the project does not require > Java 8.
=> Set an explicit java compatibilty

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/deps.kt, gradle/wrapper/gradle-wrapper.properties
We're using Kotshi in [http4k-connect](https://github.com/http4k/http4k-connect) and are having an issue with upgrading to 1.6 with the existing version of Kotshi due to a clash in Kotlinpoet version. I've upgraded here to 1.6.0 to make sure there's no problem - Kotshi already relies on the new version of poet so that's all cool!
Not sure how close 2.7.0 is to being rolled out but it would be amazing if it was soon! 
Keep up the great work! 😄
=> upgrade libraries and gradle, including kotlin to 1.6

compiler/src/main/kotlin/se/ansman/kotshi/renderer/DataClassAdapterRenderer.kt, tests/src/test/kotlin/se/ansman/kotshi/SealedClassWithDefaultWithoutTypeTest.kt
This fixes an issue when using `failOnUnknown` with sealed classes.
=> Correctly consume parent label keys in child adapters

README.md, api/api/api.api, api/src/main/kotlin/se/ansman/kotshi/ExperimentalKotshiApi.kt, api/src/main/kotlin/se/ansman/kotshi/JsonDefaultValue.kt, api/src/main/kotlin/se/ansman/kotshi/JsonProperty.kt, api/src/main/kotlin/se/ansman/kotshi/JsonSerializable.kt, buildSrc/build.gradle.kts, compiler/src/main/kotlin/se/ansman/kotshi/Types.kt, compiler/src/main/kotlin/se/ansman/kotshi/kapt/KotlinPoetExt.kt, compiler/src/main/kotlin/se/ansman/kotshi/ksp/generators/DataClassAdapterGenerator.kt, compiler/src/main/kotlin/se/ansman/kotshi/ksp/generators/EnumAdapterGenerator.kt, tests/src/main/kotlin/se/ansman/kotshi/CustomNames.kt, tests/src/main/kotlin/se/ansman/kotshi/SomeEnum.kt, tests/src/main/kotlin/se/ansman/kotshi/TestClass.kt, tests/src/test/kotlin/se/ansman/kotshi/TestEnums.kt
The new annotation, @JsonProperty, is preferred over @Json because of
its retention. Unlike @Json, @JsonProperty can be stripped at compile
time.
This fixes #175
=> Introduce an alternate way of customizing the serialized name

.github/workflows/gradle.yml, api/src/main/kotlin/se/ansman/kotshi/KotshiUtils.kt, api/src/test/kotlin/se/ansman/kotshi/TestKotshiUtils.kt
The implementation of equals and hashCode is specified in the javadoc
for those methods and the Kotshi implementations now follow them.
The implementation of toString has also been changed to match the Java
implementation as far as possible.
=> Fix the implementation of equals and hashCode for annotations

README.md, buildSrc/src/main/kotlin/se/ansman/kotshi/gradle/LibraryPlugin.kt, buildSrc/src/main/kotlin/se/ansman/kotshi/gradle/TestLibraryPlugin.kt, compiler/src/main/kotlin/se/ansman/kotshi/Errors.kt, compiler/src/main/kotlin/se/ansman/kotshi/KotlinpoetExt.kt, compiler/src/main/kotlin/se/ansman/kotshi/Options.kt, compiler/src/main/kotlin/se/ansman/kotshi/Types.kt, compiler/src/main/kotlin/se/ansman/kotshi/kapt/AdaptersProcessingStep.kt, compiler/src/main/kotlin/se/ansman/kotshi/kapt/FactoryProcessingStep.kt, compiler/src/main/kotlin/se/ansman/kotshi/kapt/KotshiProcessor.kt, compiler/src/main/kotlin/se/ansman/kotshi/kapt/Messagers.kt, compiler/src/main/kotlin/se/ansman/kotshi/kapt/generators/AdapterGenerator.kt, compiler/src/main/kotlin/se/ansman/kotshi/ksp/KotshiSymbolProcessor.kt, compiler/src/main/kotlin/se/ansman/kotshi/ksp/KspLoggers.kt, compiler/src/main/kotlin/se/ansman/kotshi/ksp/generators/AdapterGenerator.kt, compiler/src/main/kotlin/se/ansman/kotshi/model/GeneratedAnnotation.kt, compiler/src/main/kotlin/se/ansman/kotshi/renderer/AdapterRenderer.kt, compiler/src/main/kotlin/se/ansman/kotshi/renderer/JsonAdapterFactoryRenderer.kt, tests/kapt/src/test/kotlin/se/ansman/kotshi/KaptGeneratorTest.kt, tests/ksp/src/test/kotlin/se/ansman/kotshi/KspGeneratorTest.kt, tests/src/test/kotlin/se/ansman/kotshi/BaseGeneratorTest.kt
To be able to support KSP as well this feature has been changed to an option that can be used instead.
=> Don't add the @Generated annotation by default

compiler/src/main/kotlin/se/ansman/kotshi/renderer/JsonAdapterFactoryRenderer.kt, tests/src/main/kotlin/se/ansman/kotshi/ManuallyRegisteredAdapter.kt, tests/src/test/kotlin/se/ansman/kotshi/ManuallyRegisteredAdapterTest.kt
If there were no manually registered adapters then there would be an unused variable in the generated factory.
This fixes #192
=> Fix a bug that caused the generated factory to contain warnings

compiler/src/main/kotlin/se/ansman/kotshi/renderer/DataClassAdapterRenderer.kt, compiler/src/main/kotlin/se/ansman/kotshi/renderer/LegacyDataClassAdapterRenderer.kt, tests/src/main/kotlin/se/ansman/kotshi/ClassWithEscapedKotlinKeyword.kt, tests/src/test/kotlin/se/ansman/kotshi/BaseGeneratorTest.kt, tests/src/test/kotlin/se/ansman/kotshi/TestClassWithEscapedKotlinKeyword.kt
While playing around with Kotshi (which is very nice!) I noticed I couldn't generate an adapter for one class, because it had a field name that it probably shouldn't, `in`.
=> Render field names as names rather than literals so that they're escaped when necessary
