ansman/kotshi

compiler/src/main/kotlin/se/ansman/kotshi/AdapterKey.kt
compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
compiler/src/main/kotlin/se/ansman/kotshi/FactoryProcessingStep.kt
compiler/src/main/kotlin/se/ansman/kotshi/Property.kt
tests/src/main/kotlin/se/ansman/kotshi/TestClass.kt
tests/src/test/kotlin/se/ansman/kotshi/TestAdapterGeneration.kt

Multiple fields of the same type and qualifier will now use the same
adapter.

Optimize the adapter generation

---

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
tests/src/main/kotlin/se/ansman/kotshi/ClassWithWeirdNames.kt

Use NameAllocator for adapter fields, locals

---

compiler/src/main/kotlin/se/ansman/kotshi/AdapterKey.kt
compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
tests/src/main/kotlin/se/ansman/kotshi/ClassWithBoundGeneric.kt

Fix an issue with generics being used as generic type arguments

---

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
compiler/src/main/kotlin/se/ansman/kotshi/ComplexDefaultValueProvider.kt
compiler/src/main/kotlin/se/ansman/kotshi/DefaultValueProvider.kt
compiler/src/main/kotlin/se/ansman/kotshi/FixedDefaultValueProvider.kt
compiler/src/main/kotlin/se/ansman/kotshi/Property.kt

This fixes #25
@JakeWharton Please review

Skip generating a helper boolean if it's not needed

---

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
tests/src/main/kotlin/se/ansman/kotshi/MultipleJsonQualifiers.kt
tests/src/test/kotlin/se/ansman/kotshi/TestAdapterGeneration.kt

And pass in an unmodifiable set to adapter factories.

Add a test for multiple JsonQualifiers.

---

api/src/main/kotlin/se/ansman/kotshi/NamedJsonAdapter.kt
api/src/main/kotlin/se/ansman/kotshi/NullSafeJsonAdapter.kt
compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
tests/src/test/kotlin/se/ansman/kotshi/TestAdapterGeneration.kt

Let the generated adapters implement toString

---

compiler/src/main/kotlin/se/ansman/kotshi/AdapterKey.kt
compiler/src/main/kotlin/se/ansman/kotshi/Property.kt
compiler/src/main/kotlin/se/ansman/kotshi/TypeNameExt.kt
tests/src/main/kotlin/se/ansman/kotshi/Wildcards.kt

Fix a bug when using generics with wildcards

---

compiler/src/main/kotlin/se/ansman/kotshi/FactoryProcessingStep.kt

Allow the pre 1.0 way of implementing the factory

---

compiler/src/main/kotlin/se/ansman/kotshi/AdapterKey.kt
compiler/src/main/kotlin/se/ansman/kotshi/Property.kt
compiler/src/main/kotlin/se/ansman/kotshi/TypeNameExt.kt
tests/src/main/kotlin/se/ansman/kotshi/Wildcards.kt

Treat wildcards as the upper/lower bound

---

compiler/src/main/kotlin/se/ansman/kotshi/VariableElementExt.kt
tests/src/main/kotlin/se/ansman/kotshi/ClassWithWeirdNames.kt

Fix a bug regarding getter name matching

---

compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
compiler/src/main/kotlin/se/ansman/kotshi/MethodSpecExt.kt
tests/src/main/kotlin/se/ansman/kotshi/EmptyClass.kt
tests/src/test/kotlin/se/ansman/kotshi/TestAdapterGeneration.kt

Here is the generated adapter for EmptyClass:
```java
@Generated("se.ansman.kotshi.KotshiProcessor")
public final class KotshiEmptyClassJsonAdapter extends NamedJsonAdapter<EmptyClass> {
public KotshiEmptyClassJsonAdapter() {
super("KotshiJsonAdapter(EmptyClass)");
}
@Override
public void toJson(JsonWriter writer, EmptyClass value) throws IOException {
if (value == null) {
writer.nullValue();
} else {
writer
.beginObject()
.endObject();
}
}
@Override
public EmptyClass fromJson(JsonReader reader) throws IOException {
switch (reader.peek()) {
case NULL: {
return reader.nextNull();
}
case BEGIN_OBJECT: {
reader.skipValue();
return new EmptyClass();
}
default: {
// Will throw an exception
reader.beginObject();
throw new AssertionError();
}
}
}
}
```

Implement support for empty classes

---

compiler/src/main/kotlin/se/ansman/kotshi/FactoryProcessingStep.kt

Fix a crash that would happens when only generic adapters are used

---

compiler/src/main/resources/META-INF/gradle/incremental.annotation.processors

Make the processor incremental

---

compiler/src/main/kotlin/se/ansman/kotshi/FactoryProcessingStep.kt

Sort the adapters in the factory by name

---

api/build.gradle
build.gradle
compiler/build.gradle
compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
compiler/src/main/kotlin/se/ansman/kotshi/FactoryProcessingStep.kt
compiler/src/main/kotlin/se/ansman/kotshi/KotshiProcessor.kt
compiler/src/main/kotlin/se/ansman/kotshi/Type.kt
compiler/src/main/resources/META-INF/gradle/incremental.annotation.processors
gradle/wrapper/gradle-wrapper.properties
tests/build.gradle

Fix the incremental part of the processor

---

README.md
api/src/main/kotlin/se/ansman/kotshi/JsonDefaultValue.kt
api/src/main/kotlin/se/ansman/kotshi/JsonSerializable.kt
build.gradle
compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
compiler/src/main/kotlin/se/ansman/kotshi/KotlinpoetExt.kt
compiler/src/main/kotlin/se/ansman/kotshi/Property.kt
gradle.properties
tests/src/main/kotlin/se/ansman/kotshi/ClassWithWeirdNames.kt
tests/src/main/kotlin/se/ansman/kotshi/SomeEnum.kt
tests/src/test/kotlin/se/ansman/kotshi/TestEnums.kt

Depends on https://github.com/square/kotlinpoet/pull/866

Support generating adapters for enums

---

api/src/main/kotlin/se/ansman/kotshi/KotshiUtils.kt
build.gradle
compiler/build.gradle
compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
gradle/kotlin.gradle
tests/src/main/kotlin/se/ansman/kotshi/QualifierWithArguments.kt
tests/src/main/kotlin/se/ansman/kotshi/SomeEnum.kt
tests/src/test/kotlin/se/ansman/kotshi/TestQualifiersWithArguments.kt

This fixes #60 and supersedes #62
This PR depends on https://github.com/square/kotlinpoet/pull/865

Support JsonQualifiers with arguments

---

api/src/main/kotlin/se/ansman/kotshi/JsonSerializable.kt
api/src/main/kotlin/se/ansman/kotshi/KotshiJsonAdapterFactory.kt
api/src/main/kotlin/se/ansman/kotshi/SerializeNulls.kt
compiler/src/main/kotlin/se/ansman/kotshi/AdaptersProcessingStep.kt
tests/src/main/kotlin/se/ansman/kotshi/ClassWithSerializeNulls.kt
tests/src/test/kotlin/se/ansman/kotshi/TestSerializeNulls.kt

Allow enabling or disabling null serialization per adapter

---

compiler/src/main/kotlin/se/ansman/kotshi/generators/DataClassAdapterGenerator.kt
compiler/src/main/kotlin/se/ansman/kotshi/generators/ObjectAdapterGenerator.kt

Instead of manually looping and skipping names and values skipValue is
used.

Slightly improve reading kotlin objects

---

build.gradle
compiler/src/main/kotlin/se/ansman/kotshi/KotshiProcessor.kt
compiler/src/main/kotlin/se/ansman/kotshi/generators/DataClassAdapterGenerator.kt
gradle/maven-kotlin.gradle

There isn't an update to the metadata library yet so that hasn't been updated.

Update to Kotlin 1.4

---

.github/workflows/gradle.yml
.run/Test.run.xml
README.md
compiler/src/main/kotlin/se/ansman/kotshi/TypeNames.kt
compiler/src/main/kotlin/se/ansman/kotshi/Types.kt
compiler/src/main/kotlin/se/ansman/kotshi/kapt/AdaptersProcessingStep.kt
compiler/src/main/kotlin/se/ansman/kotshi/kapt/KotshiProcessor.kt
compiler/src/main/kotlin/se/ansman/kotshi/kapt/generators/AdapterGenerator.kt
compiler/src/main/kotlin/se/ansman/kotshi/ksp/KotshiSymbolProcessor.kt
compiler/src/main/kotlin/se/ansman/kotshi/ksp/generators/AdapterGenerator.kt
compiler/src/main/kotlin/se/ansman/kotshi/model/GeneratableJsonAdapter.kt
compiler/src/main/kotlin/se/ansman/kotshi/renderer/AdapterRenderer.kt
compiler/src/main/kotlin/se/ansman/kotshi/renderer/JsonAdapterFactoryRenderer.kt
compiler/src/main/kotlin/se/ansman/kotshi/renderer/LegacyDataClassAdapterRenderer.kt
tests/kapt/build.gradle.kts
tests/ksp/build.gradle.kts
tests/src/main/kotlin/se/ansman/kotshi/DefaultValues.kt

This behavior can be opted out from using the kotshi.useLegacyDataClassRenderer option.

Call the default values constructor using reflection

---

compiler/src/main/kotlin/se/ansman/kotshi/model/Property.kt
compiler/src/main/kotlin/se/ansman/kotshi/renderer/DataClassAdapterRenderer.kt
tests/src/main/kotlin/se/ansman/kotshi/Issue199.kt

Fix an edge case when a property has the same name as a type

---

.github/workflows/gradle.yml
compiler/src/main/kotlin/se/ansman/kotshi/kapt/KotshiProcessor.kt
compiler/src/main/kotlin/se/ansman/kotshi/ksp/annotations.kt
compiler/src/main/kotlin/se/ansman/kotshi/ksp/generators/DataClassAdapterGenerator.kt
gradle-plugin/src/main/kotlin/test-library.gradle.kts
tests/src/test/kotlin/se/ansman/kotshi/BaseGeneratorTest.kt
tests/src/test/kotlin/se/ansman/kotshi/IgnoredPropertiesTest.kt
tests/src/test/kotlin/se/ansman/kotshi/ManuallyRegisteredAdapterTest.kt
tests/src/test/kotlin/se/ansman/kotshi/Moshis.kt
tests/src/test/kotlin/se/ansman/kotshi/globals.kt

Ensure Kotshi runs on the oldest supported Moshi version
